### ISSUE TITLE
Claude.ft.Aleph1.exe - system error

### ISSUE THREAD

**Issue by jasoncharles** [ezetech/anthropic-gui#76]
Hi, 
Thanks for this project.

When I run Claude.ft.Aleph1.exe downloaded from https://github.com/ezetech/anthropic-gui/releases/tag/release I get the following error: 

The code execution cannot proceed because ffmpeg.dll was not found. Reinstalling the program may fix this problem.

I am running it on windows 11. Do you have a link to the required ffmpeg.dll file.

Thanks
Jason

**Comment by mlconst** [comment]
Hi @jasoncharles , thanks for the feedback. Fixed, can you check again, please?
