### ISSUE TITLE
How can I get Anthropic API Key?

### ISSUE THREAD

**Issue by qcgm1978** [ezetech/anthropic-gui#77]
The website said [Our API is currently in a closed beta. You can indicate your interest in our API here. If you previously expressed interest in our API, we have your information on file and will contact you when our API is more widely available.](https://support.anthropic.com/en/articles/8114521-how-can-i-access-the-claude-api)

So what can I do is waiting for the result?

**Comment by mlconst** [comment]
@qcgm1978 unfortunately, we can't speed up the review, so need to wait until they send you the API key.
